### ISSUE TITLE
[ENH]: elecpriceimport.import_json -- High / Low Tariff -- mapping 24 h price data to correct start time

### ISSUE THREAD

**Issue by SchaafAlexander** [Akkudoktor-EOS/EOS#807]
### Describe the enhancement or feature request:

**Target:**

- Using high / low tariff like Octopus Go  or Heat within EOS.

- Entering manually the price into 24 (h) slots of elecpriceimport.import_json.

- EOS automatically mapping current time to the correct slot of 24 (h) values

![Image](https://github.com/user-attachments/assets/66b4ab69-ccf5-43db-a1b4-29b62c255665)

**Current Issue**

- Continious Optimization always takes the first value of the 24 (h) slots mapping to the hour of the start of the optimization run

<img width="1003" height="563" alt="Image" src="https://github.com/user-attachments/assets/d5538ef2-79de-4e12-baa6-7130b18f3e10" />

**Solution**

- Mapping current time of Optimization run start to the correct 24 (h) slot of the  elecpriceimport.import_json

**Comment by b0661** [comment]
Hello @SchaafAlexander,

when importing prediction data you can use the JSON format described here: https://akkudoktor-eos.readthedocs.io/en/latest/akkudoktoreos/prediction.html#datetimedata.

If you don't provide the "start_datetime" EOS defaults to the current optimization start_datetime. If you don't provide the "interval" EOS defaults to 1 hour.

Your issue:
> Continious Optimization always takes the first value of the 24 (h) slots mapping to the hour of the start of the optimization run

is due to the missing "start_datetime".

**Comment by b0661** [comment]
With #764, it should now work with the format:

```json
    {
        "start_datetime": "2024-01-01 00:00:00",
        "interval": "1 hour",
        "<prediction key>": [value, value, ...],
        "<prediction key>": [value, value, ...],
        ...
    }
```

Interval has to be given with lowercase (doc is wrong here). To add this string to the configuration you have to enclose it with quotes '{ "start_da ... }'. Outer quotes will be removed before the string is processed for import by json.loads().

**Comment by SchaafAlexander** [comment]
Am I still doing something wrong?

<img width="1577" height="246" alt="Image" src="https://github.com/user-attachments/assets/66d40c4f-afce-430e-99b6-eac6df9a5a49" />
<img width="1534" height="489" alt="Image" src="https://github.com/user-attachments/assets/4ba7b660-92e6-4859-8dac-2fe97ef1fa66" />

**Comment by b0661** [comment]
Could you please try to set the actual date (you set 2024-01-01) as start datetime. Also change interval to "1 hour". Lowercase is needed here.

**Comment by SchaafAlexander** [comment]
@b0661 We are nearly there :-)
I still see one small flaw.

so the correct syntax working:

<img width="1584" height="302" alt="Image" src="https://github.com/user-attachments/assets/11807b8a-0e22-4cd2-86c8-9f83f0d638cc" />

Result:

<img width="1564" height="472" alt="Image" src="https://github.com/user-attachments/assets/0828ca07-fe71-4478-93e7-1a3f41c4880e" />

The issue in my opinion, the influence of the date as shown below.
If I enter tomorrow 2025-12-16 as start date one can see it best.

<img width="1558" height="282" alt="Image" src="https://github.com/user-attachments/assets/d75418d0-8c4e-43db-98d2-b01dcded7f82" />

<img width="761" height="451" alt="Image" src="https://github.com/user-attachments/assets/f06f873a-e793-423e-afb9-c4c65e31a944" />

Everything before that date has the value of the first slot, everything afterwards follows the entered schema.
BUT it never repeats the pattern, due to the influence of the date.

For high / low tariffs, the intervall and the needed amount of entries (24/96) should be the only things one should need to enter in the final solution, in my opinion :-)

Or do I overlook other scenarios here?

Thanks!

**Comment by cp-fabian-pittroff** [comment]
Hello there, I stumbled across the same issue / missing feature ([Forum](https://akkudoktor.net/t/flexible-strompreise-fuer-die-optimierung-nutzen/34843/2)).

I didn't had the time to play around more and write a feature request. For me I added a Node-Red Update to set the price information 3 days ahead.

It would be nice to configure the pricing information as repeating intervals.

```json
{
    "start_datetime": "2025-12-15 00:00:00",
    "type": "repeating",
    "interval": "1 hour",
    "tz": "Europe/Berlin",
    "dtypes": { "elecprice_marketprice_wh": "float64" },
    "elecprice_marketprice_wh": [0.0001653, 0.0001653,...]
}
```

**Comment by SchaafAlexander** [comment]
@b0661 Would this be feasible, to adjust the input, to be "repeating"?

Thanks :-)

**Comment by b0661** [comment]
> [@b0661](https://github.com/b0661) Would this be feasible, to adjust the input, to be "repeating"?

Yes, I did a short sketch but do not have time to work on it now. The idea is to use the already available TimeWindows to define fixed price information. TimeWindows are very flexible. You can define them for certain days only, ...

```python
class ElecPriceFixedCommonSettings(SettingsBaseModel):
    """Common configuration settings for fixed electricity pricing.

    This model defines a fixed electricity price schedule using a sequence
    of time windows. Each window specifies a time interval and the electricity
    price applicable during that interval.
    """

    time_windows: Optional[ElecPriceTimeWindowSequence] = Field(
        default=None,
        json_schema_extra={
            "description": (
                "Sequence of electricity price time windows defining the fixed "
                "price schedule. If not provided, no fixed pricing is applied."
            ),
            "examples": [
                {
                    "windows": [
                        {
                            "start_time": "00:00",
                            "duration": "8 hours",
                            "electricity_price_kwh": 0.288,
                        },
                        {
                            "start_time": "08:00",
                            "duration": "16 hours",
                            "electricity_price_kwh": 0.34,
                        },
                    ],
                }
            ],
        },
    )
```
